name: App Deployment
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy app
        run: |
          cd ${{ secrets.WORK_DIR }}
          git pull

          echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" > .env
          echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > postgres.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> postgres.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> postgres.env

          echo "${{ secrets.ROOT_PASSWORD }}" | sudo -S docker-compose stop
          echo "${{ secrets.ROOT_PASSWORD }}" | sudo -S docker-compose build
          echo "${{ secrets.ROOT_PASSWORD }}" | sudo -S docker-compose up -d
